import { Plugin } from 'vite';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface ApiTypesGeneratorOptions {
    apiDir?: string;
    typesDir?: string;
    typesFileName?: string;
    verbose?: boolean;
}

export default function vitePluginApiTypes(options: ApiTypesGeneratorOptions = {}): Plugin {
    const {
        apiDir = 'src/api',
        typesDir = 'src',
        typesFileName = 'api-types.d.ts',
        verbose = true
    } = options;

    let rootDir = '';

    const log = (message: string) => {
        if (verbose) {
            console.log(`[vite-plugin-api-types] ${message}`);
        }
    };

    const generateApiTypes = () => {
        try {
            const resolvedApiDir = path.resolve(rootDir, apiDir);

            if (!fs.existsSync(resolvedApiDir)) {
                log(`API directory not found: ${resolvedApiDir}`);
                return;
            }

            const files = fs
                .readdirSync(resolvedApiDir)
                .filter(
                    (file) => file.endsWith('.ts') && !file.endsWith('.d.ts') && file !== 'index.ts'
                );

            if (files.length === 0) {
                log('No API modules found');
                return;
            }

            // 生成适配命名导出的类型定义
            const moduleTypes = files
                .map((file) => {
                    const moduleName = file.replace('.ts', '');
                    // 使用整个模块的导出，而不是默认导出
                    return `  ${moduleName}: typeof import('./api/${moduleName}');`;
                })
                .join('\n');

            const content = `// Auto-generated by vite-plugin-api-types
  // DO NOT EDIT THIS FILE MANUALLY
  // Generated at: ${new Date().toISOString()}
  
  export type ApiModules = {
  ${moduleTypes}
  };
  
  export type ApiType = ApiModules;
  
  // 导出每个模块的单独类型
  ${files
      .map((file) => {
          const moduleName = file.replace('.ts', '');
          const typeName = moduleName.charAt(0).toUpperCase() + moduleName.slice(1) + 'Module';
          return `export type ${typeName} = typeof import('./api/${moduleName}');`;
      })
      .join('\n')}
  `;

            const resolvedTypesDir = path.resolve(rootDir, typesDir);
            if (!fs.existsSync(resolvedTypesDir)) {
                fs.mkdirSync(resolvedTypesDir, { recursive: true });
            }

            const outputPath = path.join(resolvedTypesDir, typesFileName);
            fs.writeFileSync(outputPath, content);

            log(
                `✅ Generated types for ${files.length} API modules: ${files
                    .map((f) => f.replace('.ts', ''))
                    .join(', ')}`
            );

            return files;
        } catch (error) {
            console.error('❌ Failed to generate API types:', error);
        }
    };

    return {
        name: 'vite-plugin-api-types',
        configResolved(config) {
            rootDir = config.root || process.cwd();
            log(`Initialized with API directory: ${path.resolve(rootDir, apiDir)}`);
            // 在配置解析后立即生成类型
            generateApiTypes();
        },
        buildStart() {
            generateApiTypes();
        },
        configureServer(server) {
            const resolvedApiDir = path.resolve(rootDir, apiDir);

            const handleFileChange = (filePath: string) => {
                if (
                    filePath.includes(resolvedApiDir) &&
                    filePath.endsWith('.ts') &&
                    !filePath.endsWith('.d.ts') &&
                    !filePath.endsWith('index.ts')
                ) {
                    log(`API file changed: ${path.relative(rootDir, filePath)}`);
                    generateApiTypes();
                }
            };

            server.watcher.on('add', handleFileChange);
            server.watcher.on('change', handleFileChange);
            server.watcher.on('unlink', handleFileChange);
        }
    };
}
